// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syetcsrhcnvapoehrtjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5ZXRjc3JoY252YXBvZWhydGp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMzgxNDcsImV4cCI6MjA1NzYxNDE0N30.pfdYEn7_bxHM5lULxC-rT8JwC1MVIgP1IcvZJ1NrgMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);